/*package com.example.itis_shop.resources

import com.example.itis_shop.storage.Product


object SneakersRepository{
    /*val sneakers: List<Product> = listOf(
        Product("Nike Dankey", 150, "Super mega krutue", "https://krostore.ru/images/product/l/5516-nike-sb-dunk-low-green-paisley-29a690.jpg"),
        Product("Nike Dankey", 150, "Super mega krutue", "https://krostore.ru/images/product/l/5516-nike-sb-dunk-low-green-paisley-29a690.jpg"),
        Product("Nike Dankey", 150, "Super mega krutue", "https://krostore.ru/images/product/l/5516-nike-sb-dunk-low-green-paisley-29a690.jpg"),
        Product("Nike Dankey", 150, "Super mega krutue", "https://krostore.ru/images/product/l/5516-nike-sb-dunk-low-green-paisley-29a690.jpg"),
        Product("Nike Dankey", 150, "Super mega krutue", "https://krostore.ru/images/product/l/5516-nike-sb-dunk-low-green-paisley-29a690.jpg"),
        Product("Nike Dankey", 150, "Super mega krutue", "https://krostore.ru/images/product/l/5516-nike-sb-dunk-low-green-paisley-29a690.jpg"),
        Product("Nike Dankey", 150, "Super mega krutue", "https://krostore.ru/images/product/l/5516-nike-sb-dunk-low-green-paisley-29a690.jpg"),
        Product("Nike Dankey", 150, "Super mega krutue", "https://krostore.ru/images/product/l/5516-nike-sb-dunk-low-green-paisley-29a690.jpg"),
        Product("Nike Dankey", 150, "Super mega krutue", "https://krostore.ru/images/product/l/5516-nike-sb-dunk-low-green-paisley-29a690.jpg"),
        Product("Nike Dankey", 150, "Super mega krutue", "https://krostore.ru/images/product/l/5516-nike-sb-dunk-low-green-paisley-29a690.jpg"),
        Product("Nike Dankey", 150, "Super mega krutue", "https://krostore.ru/images/product/l/5516-nike-sb-dunk-low-green-paisley-29a690.jpg"),
        Product("Nike Dankey", 150, "Super mega krutue", "https://krostore.ru/images/product/l/5516-nike-sb-dunk-low-green-paisley-29a690.jpg"),
        Product("Nike Dankey", 150, "Super mega krutue", "https://krostore.ru/images/product/l/5516-nike-sb-dunk-low-green-paisley-29a690.jpg")
    )*/

    var products: List<Product> = listOf(
        Product("Converse Chuck 70", 199,"Кеды Converse All Star Chuck ’70 - это классика с современными деталями. Они отличаются более высоким резиновым покрытием на подошве, мягкой стелькой, обеспечивающей длительный комфорт, и более прочным резиновым мыском.","https://static.street-beat.ru/upload/resize_cache/iblock/2a6/500_500_1/gv6dzjvt9otnamcxn3379wo6imb7r8xh.jpg"),
        Product("Reebok BB 4000 II",129,"Классическая модель, переродившаяся в новом поколении. Вдохновлённые баскетбольной площадкой и прославившиеся на улицах кроссовки Reebok теперь доступны в высокой и низкой версиях.","https://superstep.ru/upload/resize_cache/iblock/05b/2hzf550tkok2q71w7zngg7dc8fc61grh/800_800_2/RB100074941R00.jpg"),
        Product("Nike Dunk Low Mini Swoosh",229,"Модель Nike Dunk Low с верхом из кожи серого цвета с сетчатыми язычками и подкладкой. Черные накладки из гладкой кожи с текстурированным кожаным свушем на каждой стороне отсылают к образу панды.","https://superstep.ru/upload/resize_cache/iblock/3d5/bdpt28vhwx43az2bz6o369i7xxi2ffx6/800_800_2/NKFN7808001.jpg"),
        Product("Puma CA Pro Lux III",100,"Кроссовки CA Pro вдохновлены оригинальной моделью California, которую выпустили в 80-х годах. Классический и одновременно современный вид, с перфорированным мыском","https://superstep.ru/upload/resize_cache/iblock/195/2vmu66vpk9wjg9dneaf5606x6ke74nuh/800_800_2/PM39520302.jpg"),
        Product("Reebok CLUB C REVENGE",119,"Кроссовки Reebok CLUB C REVENGE в ретро-теннистой стилистике с контрастным логотипом, боковыми полосами и задником дополнят знаковый образ","https://superstep.ru/upload/resize_cache/iblock/ccd/mujsc86xa5kbsxdur2da8n6jbjldtfr1/800_800_2/RB100075005R00.jpg"),
        Product("Vans Old Skool",88,"Классика от Vans, Old Skool - модель, на которых впервые появилась знаменитая белая полоса. Верх выполнен из плотного канваса и натуральной кожи.","https://superstep.ru/upload/resize_cache/iblock/b84/3r68ex5d8kisg430jryzu4wfk6l3vszz/800_800_2/VN000D3HY281.jpg"),
        Product("Asics JAPAN S",119,"Кроссовки JAPAN S созданы на основе одной из моделей, выпущенных в стиле ретро. Винтажная баскетбольная эстетика JAPAN S также сочетается с культовыми деталями, характерными для кортов, которую носили баскетболисты 1980-х годов","https://superstep.ru/upload/resize_cache/iblock/354/hrbs1scetskivsu0kroxn6uqghbg1qds/800_800_2/AS1191A328104.jpg"),
        Product("AIR FORCE 1 '07",229,"Самая узнаваемая модель Nike Air Force 1 '07 сейчас можно точно назвать классикой бренда. Изначально разработанная для баскетбола система амортизации Nike Air обеспечивает легкость и комфорт на весь день. ","https://superstep.ru/upload/resize_cache/iblock/93c/vom7t758af1z7s4q2i8xwdb9ron94n3x/800_800_2/NKDV7584001.jpg"),
        Product("Adidas SAMBAE",190,"Если перенестись в 1960-е годы, то можно обнаружить, что профессиональные футболисты носят adidas Samba, точно такие же, как эта модель. Ну, почти такие же. Обновленные для нового поколения, они имеют мягкий носок, который обеспечит комфорт","https://superstep.ru/upload/resize_cache/iblock/306/u90v023w2wfakooj8q7fwi8mlpbt7b2o/800_800_2/ADID0440R00.jpg"),
        Product("Nike DUNK LOW ESS SNKR",229,"Кроссовки DUNK LOW ESS SNKR, отделанные роскошной гладкой атласной тканью, выглядят более нарядно, чем обычные кроссовки, но по-прежнему достаточно спортивные. ","https://superstep.ru/upload/resize_cache/iblock/5e1/gxofp14130e0rh0fqvbesq16yu2qspjq/800_800_2/NKDX5931001.jpg"),
        Product("New Balance 550",209,"Для всех ценителей винтажных моделей мы рады представить модель 550 от New Balance! В 1989 году эта модель была разработана специально для баскетбола, сегодня же она дополнит стильный повседневный образ. ","https://superstep.ru/upload/resize_cache/iblock/436/fvf2thy2wchh8zdej62k3998cokjon22/800_800_2/NBBBW550DP.jpg"),
        Product("Nike Air Force 1 '07",229,"Nike Air Force 1 '07 EasyOn со специальной конструкцией пятки для лёгкого одевания без помощи рук. Технология FlyEase позволяет наступить на заднюю часть, чтобы она сложилась, а нога проскользнула внутрь, после чего задник защёлкнется обратно.","https://superstep.ru/upload/resize_cache/iblock/4fa/1csv843t4mtce8ardoicx2ij56snul4s/800_800_2/NKDX5883100.jpg"),
        Product("New Balance M2002",259,"Модель New Balance 2002R вдохновлена беговыми кроссовками 2000-х годов и уже покорила сердца всех модников. Верх из прочного рипстопа дополнен вставками из замши с «рваными» краями, а резиновая подошва оснащена инновационными технологиями бренда.","https://superstep.ru/upload/resize_cache/iblock/94b/tde188fynrc71f0omam24982f6kwt834/800_800_2/NBM2002RIA.jpg"),
        Product("Anta Millennium-Glacier",97,"Повседневные кроссовки в культовом ретро-фасоне Millennium-Glacier. Вставки из ТПУ по бокам для поддержки и фиксации стопы делают прогулки безопаснее. Верх кроссовка из комбинированных материалов выполнен с технологией, упрощающей чистку","https://superstep.ru/upload/resize_cache/iblock/340/xiym3gd1who2fxt8hlkao54m2j244y32/800_800_2/AN8123388811.jpg"),
        Product("Puma Morphic Athletic",129,"Встречай Puma Morphic - новые ретро кроссовки. Эта спортивная модель отличается прогрессивным и динамичным видом, что делает эти кроссовки идеальными. Эта модель имеет двухцветную сетчатую основу с синтетическими накладками.","https://superstep.ru/upload/resize_cache/iblock/34b/454i8g55j1vcclkusi6gs2jwyw23idbl/800_800_2/PM39591902.jpg"),
        Product("Reebok CLUB C REVENGE",119,"Кроссовки Reebok CLUB C REVENGE в ретро-теннистой стилистике с контрастным логотипом, боковыми полосами и задником дополнят знаковый образ. Наследие прошлого — укороченный верх и прочная резиновая подошва Cupsole","https://superstep.ru/upload/resize_cache/iblock/f9a/ow2a5pu7ib0r6kw0octfzo1xtlmy7lvt/800_800_2/RB100074210R00.jpg"),
        Product("Puma CA Pro Sport Lth",110,"Кеды PUMA California, выпущенные в 80-х, оставили свой след в уличной моде. Новая итерация линейки, кеды CA Pro Sport, обладает характерными чертами оригинала, включая лаконичный силуэт, но дополнена перфорацией и формованной промежуточной подошвой","https://superstep.ru/upload/resize_cache/iblock/2d8/isnt3vyb8642l4klc3qu4n9wgziao6ly/800_800_2/PM39328009.jpg"),
        Product("New Balance MR530",119,"New Balance MR530 — это классика винтажного бегового стиля. Массивные кроссовки в стиле dad shoes созданы для тех, кто ценит простоту и комфорт. Верх выполнен из сетки с плотными вставками для дополнительной поддержки.","https://superstep.ru/upload/resize_cache/iblock/8fb/uvcmfq9kav3rt8f4986r1p7hf1osc0y2/800_800_2/NBMR530RA.jpg"),
        Product("Puma RS-X '40th Anniversary",169,"Верх - 100% текстиль, подкладка - 100% текстиль, низ - 100% резина. Страна производитель: ВЬЕТНАМ","https://superstep.ru/upload/resize_cache/iblock/40c/xa13nk2exlytrhu39rpoefcfujy7a1n1/800_800_2/PM39533901.jpg"),
        Product("Vans Knu Skool",90,"Стиль 90-х с первого взгляда, Vans недавно обратился к своим архивам, чтобы выпустить Knu Skool, который напоминает нам о тех временах, когда модели для скейтбординга были шире и толще. Пара имеет прочный замшевый верх, созданный для того, чтобы выдерживать спортивную практику","https://superstep.ru/upload/resize_cache/iblock/5fd/721b0x661rte4biypogttdwpdq5gxy3y/800_800_2/VN0009QC6BT1.jpg"),
        Product("Adidas CAMPUS 00s",136,"Эпоха скейтбординга 2000-х годов оставила неизгладимый след в культуре и стиле. Эти кроссовки adidas Campus – свидетельство стойкости этого десятилетия, сочетающее детали дизайна и первоклассные материалы в одном удобном для ношения образе.","https://superstep.ru/upload/resize_cache/iblock/d94/ak4nznq9eseoskvw49wi727f8pv7fmex/800_800_2/ADHQ8708R00.jpg"),
        Product("Puma Morphic Suede",97,"Встречай Puma Morphic Suede - новые ретро кроссовки. Эта спортивная модель отличается прогрессивным и динамичным видом, что делает эти кроссовки идеальными. Эта модель имеет двухцветную сетчатую основу с синтетическими накладками.","https://superstep.ru/upload/resize_cache/iblock/4e2/gxk7irjfa52xol6di4v276ve0ca9d4g1/800_800_2/PM39668702.jpg"),
        Product("Puma BMW MMS Velophasis",132,"BMW MMS Velophasis — это стильные и дерзкие кроссовки, сочетающие элементы дизайна гоночных болидов BMW MMS и настоящий уличный стиль 2000-х.","https://superstep.ru/upload/resize_cache/iblock/9ef/jdabnfh1l6l2g6uwdwd427lwp07z31ls/800_800_2/PM30829501.jpg"),
        Product("Reebok CLUB C DOUBLE REVENGE",119,"Кроссовки CLUB C DOUBLE REVENGE изготовлены из высококачественных материалов, которые обеспечивают комфорт и поддержку во время тренировок и повседневного ношения. Одна из главных технологий, примененных в этих кроссовках - это двойная подошва, которая обеспечивает дополнительную амортизацию и улучшенную поддержку стопы.","https://superstep.ru/upload/iblock/afb/c7a1p2j9y4jems3dmxj3q1q6o2zt5qwp/RB100074268R00.jpg"),
        Product("Puma RS-X '40th Anniversary'",169,"Верх - 100% текстиль, подкладка - 100% текстиль, низ - 100% резина. Страна производитель: ВЬЕТНАМ","https://superstep.ru/upload/resize_cache/iblock/787/ijp3hww4qtpmtwog21znx1bsda5lx17d/800_800_2/PM39533902.jpg"),
        Product("Anta MILLENNIUM 7.0",88,"Повседневные кроссовки Millennium 7.0 из коллекции Running Culture создают стильный образ. Дышащая сетка, текстурированный нубук и замшевые вставки создают классический винтажный образ. Подошва сделана c использованием технологичной пены, которая обеспечивает оптимальную мягкость и упругость. В подошве используется пена A-FLASHEDGE","https://superstep.ru/upload/resize_cache/iblock/ced/a2rpctrm37f9iqy5uzlhz92ar0td3xqy/800_800_2/AN8224288903.jpg"),
        Product("Puma LUCY",88,"Кроссовки в стиле chunky ANTA LUCY — модель на каждый день, которая поможет тебе выделяться на улице. Пара сочетает в себе эстетику ретро и современные тренды. В конструкции верха используются замша,сетка и вставки из ТПУ, создающие изящную многослойность в винтажном стиле.","https://superstep.ru/upload/resize_cache/iblock/f07/zznd4266kjzpi299qp0yzo25caufb3ay/800_800_2/AN8224188514.jpg"),
        Product("BB 4000 II",129,"BB 4000 ll снова в строю. Классическая модель, переродившаяся в новом поколении. Вдохновлённые баскетбольной площадкой и прославившиеся на улицах кроссовки Reebok теперь доступны в высокой и низкой версиях. Ретро-силуэт напоминает о наследии бренда 80-х годов, верх выполнен из мягкой натуральной кожи премиум качества","https://superstep.ru/upload/resize_cache/iblock/216/5r1tvefa0c7u2006sickq8bh41r3kjkn/800_800_2/RB100033737R00.jpg"),
        Product("Adidas OZWEEGO",158,"90-е годы были эпохой яркой и экспрессивной моды. Их влияние отчетливо видно в этих кроссовках adidas OZWEEGO, которые из культовой беговой модели превратились в икону уличного стиля. К тому же, безупречно комфортную. За это можно поблагодарить подошву с амортизацией Adiprene, которая смягчает каждый шаг.","https://superstep.ru/upload/resize_cache/iblock/db4/s8pz01kd2wmthcm02m8gsiiinzq04fd6/800_800_2/ADGY6177R00.jpg"),
        Product("Adidas FORUM MID",135,"Что ты выберешь? Легендарную баскетбольную модель из 80-х? Или культовые кроссовки, которые носят самые крутые рэперы? Больше выбирать не придется. Кроссовки adidas Forum доминируют на баскетбольных площадках и на улицах города. Теперь они представлены в версии с высоким верхом, которая выводит твой стиль на новый уровень.","https://superstep.ru/upload/resize_cache/iblock/e56/zxbzns2cbumr2c779fn6ff117abucgj7/800_800_2/ADIG3755R00.jpg")
    )
}
*/